AWSTemplateFormatVersion: '2010-09-09'
Parameters: {}
Resources:
  # THIS IS THE CLOUDFRONT ORIGIN
  # index.html and unsupported.html will live here
  CloudfrontLambdaEdgeS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Sub:
        - cloudfront-lambda-edge-${UniqueId}
        - UniqueId:
            Fn::Select:
            - 0
            - Fn::Split:
              - "-"
              - Fn::Select:
                - 2
                - Fn::Split:
                  - "/"
                  - Ref: AWS::StackId
  # Policy for above S3 Bucket
  CloudfrontLambdaEdgeS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn:
    - CloudfrontLambdaEdgeS3Bucket
    Properties:
      Bucket:
        Ref: CloudfrontLambdaEdgeS3Bucket
      PolicyDocument:
        Id: PolicyForCloudFrontPrivateContent
        Statement:
        - Effect: Allow
          Principal:
            AWS:
              Fn::Sub: arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity
                ${CloudfrontLambdaEdgeCloudFrontOAI}
          Action: s3:GetObject
          Resource:
            Fn::Sub:
            - "${CloudfrontLambdaEdgeS3BucketArn}/*"
            - CloudfrontLambdaEdgeS3BucketArn:
                Fn::GetAtt:
                - CloudfrontLambdaEdgeS3Bucket
                - Arn
  # Do not let anyone access S3 content via S3 URL's
  # Only way to access is via Cloudfront
  CloudfrontLambdaEdgeCloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment:
          Fn::Sub:
          - OAI For Lambda@Edge Example ${UniqueId}
          - UniqueId:
              Fn::Select:
              - 0
              - Fn::Split:
                - "-"
                - Fn::Select:
                  - 2
                  - Fn::Split:
                    - "/"
                    - Ref: AWS::StackId
  # Cloudfront distribution config
  # The DefaultCacheBehavior -- Lambda is important here.
  # It prevents all browsers from accessing the site (except for chrome)
  CloudfrontLambdaEdgeCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn:
    - CloudfrontLambdaEdgeS3Bucket
    - CloudfrontLambdaEdgeCloudFrontOAI
    Properties:
      DistributionConfig:
        Comment:
          Fn::Sub:
          - Lambda@Edge Example ${UniqueId}
          - UniqueId:
              Fn::Select:
              - 0
              - Fn::Split:
                - "-"
                - Fn::Select:
                  - 2
                  - Fn::Split:
                    - "/"
                    - Ref: AWS::StackId
        Origins:
        - Id: CloudfrontLambdaEdgeS3BucketOriginId
          DomainName:
            Fn::GetAtt:
            - CloudfrontLambdaEdgeS3Bucket
            - RegionalDomainName
          S3OriginConfig:
            OriginAccessIdentity:
              Fn::Sub: origin-access-identity/cloudfront/${CloudfrontLambdaEdgeCloudFrontOAI}
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: CloudfrontLambdaEdgeS3BucketOriginId
          LambdaFunctionAssociations:
            # The function executes when CloudFront receives a request from a viewer and before it checks to see whether the requested object is in the edge cache.
            - EventType: viewer-request
              LambdaFunctionARN: <ADD-FUNCTION-ARN>:<ADD-FUNCTION-VERSION>
          ViewerProtocolPolicy: allow-all
          ForwardedValues:
            Headers: []
            Cookies:
              Forward: none
            QueryString: false
            QueryStringCacheKeys: []
          MinTTL: 0
          MaxTTL: 600
          DefaultTTL: 60
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        HttpVersion: http2
        PriceClass: PriceClass_All
        IPV6Enabled: true
        Enabled: true
        CustomErrorResponses:
        - ErrorCachingMinTTL: 5
          ErrorCode: 400
        - ErrorCachingMinTTL: 5
          ErrorCode: 403
        - ErrorCachingMinTTL: 5
          ErrorCode: 404
        - ErrorCachingMinTTL: 5
          ErrorCode: 405
        - ErrorCachingMinTTL: 5
          ErrorCode: 500
        - ErrorCachingMinTTL: 5
          ErrorCode: 501
        - ErrorCachingMinTTL: 5
          ErrorCode: 502
        - ErrorCachingMinTTL: 5
          ErrorCode: 503
        - ErrorCachingMinTTL: 5
          ErrorCode: 504
